version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev

  test:
    image: mcr.microsoft.com/playwright:v1.28.0-focal
    depends_on:
      - app
    working_dir: /app
    volumes:
      - .:/app
    entrypoint: ["npx", "playwright", "test"]
    environment:
      - BASE_URL=https://node_app:3000/users
