name: Build, Test, and Run Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: mcr.microsoft.com/playwright:v1.28.0-focal
        options: --entrypoint /bin/bash
        ports:
          - 3000:3000
        env:
          NODE_ENV: development
        volumes:
          - .:/app

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Set up Docker Compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
            compose-file: /github/workspace/docker-compose.yaml
            up-flags: -d

      - name: Build and Start Containers
        run: |
          docker-compose -f docker-compose.yml up -d
          docker-compose exec app npm ci  # Убедитесь, что все зависимости установлены

      - name: Show Docker container logs
        run: docker logs $(docker ps -q --filter "ancestor=mcr.microsoft.com/playwright:v1.28.0-focal")

      - name: Run homework 14 tests
        run: npx playwright test tests/hw-14-1-create-n-users.test.ts hw-14-2-get-users-by-id.test.ts hw-14-3-delete-users.test.ts

      - name: Run lesson tests
        run: npx playwright test tests/lesson-14-1-create-n-users.test.ts lesson-14-2-delete-n-users.test.ts lesson-14-3-delete-m-users-after-creating-n-users.test.ts
